---
name: Config-Model-Sshd
version: 0.103
author:
  - Dominique Dumont (ddumont at cpan dot org)
abstract: OpenSsh Sshd configuration editor
license: lgpl
resources:
  license: http://opensource.org/licenses/lgpl-license.php
requires:
  Config::Model: 0.623
  Log::Log4perl: 0
  perl: 5.8.0
recommends:
  Config::Model::CursesUI: 0
  Config::Model::TkUI: 0
provides:
  Config::Model::Sshd:
    file: lib/Config/Model/Sshd.pm
    version: 1.0692
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
